[package]
name = "log-analysis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] } 
ssh2 = "0.9"
ctrlc = "3.4.0"
crossterm = "0.26"
ratatui = { version ="0.21.0", features = ["all-widgets"]}
bitflags = "2.3"
time = { version = "0.3.11", optional = true, features = ["local-offset"] }
unicode-width = "0.1"
serde = "1.0.164"


[dev-dependencies]
anyhow = "1.0.71"
rand = "0.8"
argh = "0.1"
