[package]
authors = ["ende <endepointe@gmail.com>"]
categories = ["network programming", "log analysis"]
description = "A zeek log analysis library implemented in Rust"
name = "log-analysis"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = ["ip2location"]

ip2location = []

[dependencies]
