[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
async-graphql = "7.0.6"
async-graphql-actix-web = "7.0.6"
flate2 = "1.0.30"
serde_json = "1.0.120"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"



